Agharta/eip1014 create2
eth-classic/go-ethereum pull request #78
Opened 2019-06-20 21:35 UTC by dziabko

Implemented Create2 opcode. Passes most ConstantinopleFix tests, but fails some tests involving the SSTORE opcode under Constantinople. We do not care about the Constantinople specific tests because of the St-Petersburg fix, because in ETH they check for [old gas calculations](https://github.com/ethereum/go-ethereum/blob/25c3282cf1260bdc68c4ba9075c2bcc2f8136ea5/core/vm/gas_table.go#L116). Therefore we only care about the StPetersburg changes, and will not reflect the revoked Constantinople EIP. The create2InitCodes.json/Constantinople test fails under SSTORE except for 1 passing test where it creates a contract with 0x00 (STOP), so there’s nothing to store.

2019-06-21 05:53 UTC, soc1c commented
did you cherry-pick commits from development? rebase would be preferred if possible

2019-06-21 14:17 UTC, austinabell requested changes
I can look into technically why the tests are failing once the other stuff is cleared up :)

2019-06-21 14:17 UTC, austinabell commented on core/vm/jump_table_test.go
> +// func TestInit(t *testing.T) {
Why was it required to remove this test? If anything, shouldn't it be expanded to include Atlantis and Agharta codes?

2019-06-21 14:17 UTC, austinabell commented on core/vm/vm.go
> +		fmt.Println("OP: ", op.String())
Take out print statements when you open a PR

2019-06-21 14:17 UTC, austinabell commented on go.mod
> +	github.com/allegro/bigcache v1.2.0 // indirect
Why was it necessary to change go.mod/sum?

2019-06-21 14:17 UTC, austinabell commented on go.mod
> +	github.com/ethereum/go-ethereum v1.8.27
Definitely shouldn't have ethereum/go-ethereum dependency

2019-06-21 14:17 UTC, austinabell commented on params/protocol_params.go
> +	Sha3WordGas       uint64 = 6                  // Once per word of the SHA3 operation's data.
Why didn't you make this variable a *big.Int and use it in your create2 gas calculation? It's unused right now.

2019-06-21 14:17 UTC, austinabell commented on core/vm/jump_table.go
> +		// CREATE2: {
delete this

2019-06-21 14:17 UTC, austinabell commented on tests/init.go
> +		ExplosionBlock:           big.NewInt(0),
This only affects difficulty, which isn't tested with state tests. Doesn't affect anything here, but probably shouldn't include the declaration of it to avoid confusion. (There isn't even a need for ExplosionBlock as it is only defined in RuleSet which is just used for testing that does used)

2019-06-21 14:17 UTC, austinabell commented on core/execution.go
> +	var createAccount bool = false
that is already the default?

2019-06-21 14:29 UTC, noot requested changes
nice work, just need to clean up code a bit :)

2019-06-21 14:29 UTC, noot commented on core/execution.go
> +//They're Not using Sender nonce hash?
remove comment

2019-06-21 14:29 UTC, noot commented on core/execution.go
> +func create(env vm.Environment, caller vm.ContractRef, address, codeAddr *common.Address, codeHash common.Hash, input, code []byte, gas, gasPrice, value *big.Int, readOnly bool) ([]byte, common.Addre
was there already a create function somewhere? just wondering

2019-06-21 14:29 UTC, noot commented on core/execution.go
> +		fmt.Println("Creating new Address")
remove

2019-06-21 14:29 UTC, noot commented on core/execution.go
> +	// if codeAddr == nil {
remove commented out code in this file pls

2019-06-21 14:29 UTC, noot commented on core/vm/instructions.go
> +	// ret, addr, suberr := env.Create2(contract, input, gas, contract.Price, salt, value)
remove comment

2019-06-21 14:29 UTC, noot commented on core/vm/instructions.go
> +		// gas2         = new(big.Int).Set(contract.Gas)
remove

2019-06-21 14:29 UTC, noot commented on core/vm/instructions_test.go
> +			stack          := newstack()
remove or put in its own test btw

2019-06-21 14:29 UTC, noot commented on core/vm/jump_table.go
> +		// 	fn:      opCreate2,
why is this commented out

2019-06-21 14:29 UTC, noot commented on core/vm/vm.go
> +		fmt.Println("STACK: ", stack.Data())
please clean up this file, remove all prints

2019-06-21 14:29 UTC, noot commented on tests/state_test.go
> +		// "Constantinople":               true,
why are these commented out

2019-06-21 14:29 UTC, noot commented on tests/util.go
> +		// return core.Create(self, caller, data, gas, price, value)
remove comment

2019-06-21 14:30 UTC, austinabell commented on core/execution.go
> +func create(env vm.Environment, caller vm.ContractRef, address, codeAddr *common.Address, codeHash common.Hash, input, code []byte, gas, gasPrice, value *big.Int, readOnly bool) ([]byte, common.Addre
There is a `Create()` function that calls `exec()` iirc

2019-06-21 14:30 UTC, GregTheGreek commented
1)Please rebase this pr if possible
2) Failing tests make sense (in relation to Petersburg
Constantinopole had included changes to the gas costs of `SSTORE`, they made tests ("T1") for these changes. When the re-entrancy bug was discovered they reverted the gas cost changes in a new fork call Petersburg, and they add a new set of tests to "T1" called "Constantinople-fix" (effectively Petersburg tests). The reason is because as @dziabko pointed out ETH Geth (and im assuming other clients (still contain)[https://github.com/ethereum/go-ethereum/blob/25c3282cf1260bdc68c4ba9075c2bcc2f8136ea5/core/vm/gas_table.go#L116] the gas calculation from Constantinople. Since we don't care about the changes to SSTORE those tests found in T1 labelled **Constantinople should** be skipped, those labelled **Constantinople-fix** should be run.

Again this is only for tests pertaining to `SSTORE`

2019-06-21 14:54 UTC, noot commented
when I run tests locally I get `fatal error: runtime: out of memory`.. any ideas?

2019-06-21 19:11 UTC, steviezhang commented on core/vm/instructions.go
> +	ErrRevert                = errors.New("Execution reverted")
Should probably change the case and formatting for ErrRevert to be in line with the other errors.

2019-06-24 22:18 UTC, austinabell requested changes
If you are expecting test failures because it is invalid to test certain things, skip and explain why the tests are being skipped. The tests are failing and that needs to be resolved before merging. Otherwise looks good and I hope this passes all of the relevant tests !

2019-06-24 22:18 UTC, austinabell commented on core/execution.go
> +	ErrContractAddressCollision = errors.New("contract address collision")
Both of these are only used within the package, so no need to export them (can change to camel case)

2019-06-24 22:18 UTC, austinabell commented on tests/state_test.go
> +		// "stCreate2":        true,
Can just delete these since the test skips will not be added back in the future

2019-06-24 22:18 UTC, austinabell commented on tests/state_test.go
> +		// "ConstantinopleFix":            true,
See above

2019-06-24 22:38 UTC, dziabko commented
@noot  @soc1c @austinabell Can you please confirm that we should skip Constantinople in the test cases that involve Constantinople & ConstantinopleFix.

2019-06-25 20:01 UTC, austinabell commented on tests/state_test.go
> +		"stReturnDataTest": true,
Shouldn't be skipping this folder or stCodeSizeLimit, why were those added?

2019-06-25 20:05 UTC, austinabell commented on tests/state_test.go
> +	skipTests["stCreate2/Constantinople"] = "Only testing for ConstantinopleFix"
remove this line

2019-06-26 16:33 UTC, GregTheGreek commented
Please switch this pr's remote to https://github.com/etclabscore/go-ethereum :)

2019-06-26 19:09 UTC, closed without merging